### ISSUE TITLE
EEPROM listing

### ISSUE THREAD

**Issue by tophcodes** [DutchMaker/8-bit-Breadboard-Computer#4]
The parts list specifies 6 CAT28C16AP EEPROMs are neded for the Output and "Control Unit" modules. I've watched the Output videos and after the most recent one it looks like that requires only one EEPROM with Bens multiplexing approach. That would leave the remaining 5 EEPROMs for the Control Unit section. For that however I cannot find any videos.

The EEPROMs I found are all quite expensive (5-10€ each), so I'd like to keep the amount I buy at a minimum. Can you link me to the video that requires all these EEPROMs so I can see if they're really required or if there's perhaps any alternatives?

Thanks!

**Comment by DutchMaker** [comment]
I have not updated the parts list yet after the last video.
The 6 EEPROMS were based on shots from the very first video that shows the complete computer.
Since Ben has brought down the number of roms in the output unit from 3 to 1, the total number will come down to 4 EEPROMs for the entire computer.

I am planning several updates to the parts list and will close this issue once that is done.

**Comment by DotTech** [comment]
I have updated the parts list with a better layout and up to date parts.
For this update, I have removed the EEPROMs that have not been featured in the videos yet, until we are all sure that Ben is going to use them.
But when you are ordering parts, it's pretty safe to assume you will need 4 EEPROMs in total.
